### PR TITLE
Debug

### PR DESCRIPTION
**Pull request by petrolifero**
related to #59 

when We try to match the sum peg inside test-debug.rkt, there's a good print.

When there's need to backtrack, in some level, duplicate output is show because of 2 points : 

1) on fail , the pegvm-verbose don't is subtracted
2) as the debug text is show in the start of a `peg-rule:a` function, if that function fails, there's no way to "revoke" that output.

My try will concentrate in : 

1) complete test-debug.rkt with properly rackunit test.
2) on fail, decrement pegvm-verbose.

On output duplicate, I think the better solution is : use a list of strings.

When a function "peg-rule:a" execute, instead of print debug information, she add the string to this list.
When a fail occur, the string(or strings, if the fail is a "and") is pop out.

Finally, when peg-rule:local return, their value is saved, the list of debug is displayed, and the value saved is returned.

What do you think?

Merry Christmas!
happy New Year!

### CODE REVIEW

**Comment by petrolifero** [comment]
I add a message when pegvm-fail is called

I think in this way : when fail is called, then a rule fail. But is not the case. When a rule as `a*` is used, there's a fail call when there's no more "a".

How to differenciate a real fail, to subtract pegvm-verbose from a fake fail, indicating just a intern use of fail to derive semantics?

**Comment by petrolifero** [comment]
So, I need to add a "marker" on a expression. generated by a function call.

Something that, when fail be called, she knows if is intern or extern PEG that call's

**Comment by rain-1** [comment]
I had a look at the changes. I see it is coming along but I gather the indentation levels are not fully working yet.

Regarding the marker on expressions, we must be careful not to complicate the too much or slow it down when debugging is off.

Maybe the way PEG is implemented with continuations makes it difficult to have this style of debugging info. Is there a different style of debugging that will be easier to add?

**Comment by petrolifero** [comment]
The continuations make harder yes :).

I dont test with greater grammar to see potential problems in performance. In fact, theres no speed test here.

I dont know, but if you prefer, i can search a substitite. I want to play with this way until 1 january. If we cant see better results, i rollback and try another debug, what do you think?

**Comment by petrolifero** [comment]
I dont see how to put the marker easily.

If there's no problem, I will rollback.

One possibility was on each fail, print the pegvm state complete, but this is not semantic debug.

Can help us, but not help some people that will use the library to their parser.

I don't wanna like to run gcc and he say "There's a ciclic path in the type digraph" or something like that.

What you wanna like to see on debug? 


The great thing about PEG is composse grammar. So, is a very simple way to do unit test on grammar rules.

This debug will be good?


```
(peg (and number "+" number) "12+13" #t) 

try to parse (and number "+" number)
try to parse (and number (and "+" number))
try to parse number
...
try to parse (and "+" number")
try to parse "+"
try to parse number
...
```

I think  this is very simple to code. Is just add display on peg-compile on each rule(or putting the display ahead of the matching)

**Comment by petrolifero** [comment]
I think that the problem was that we are trying to think in a imperative way.

The problem of "know when a fail is a normal operation or a function fail" can be
resolved using TWO continuations instead of one (the sucess continuation, that we use now, and a failure continuation).

With this, a peg-rule:name function will receive two arguments.

The peg-compile will receive the two continuations and, instead of just calling pegvm-fail, will invoke the fail continuation.

The good point is : the normal fail continuation will just call pegvm-fail.

The function fail continuation will verify if pegvm-verbose exist, and if so, display something and call pegvm-fail with pegvm-verbose subtracted. In other case, just call pegvm-fail.

With this, the problem of thinking if the fail is of one type or another will be resolved by the agente that knows that, the function.

In the next days I will be very busy, but after some days I will return to this

**Comment by petrolifero** [comment]
The continuations only will think about pegvm-verbose and in the end call pegvm-fail.

In their thinkings, can display some debug and call pegvm-fail with pegvm-verbose modified. ONLY this.

Will not Interact with the pegvm in any other way.

What do you think?

**Comment by petrolifero** [comment]
Yeah, sorry about that. I could not do the change.

I make a very problematic job with this code. I will delete this branch, close this pull-request, think better and if I implement a functional debug, I will open another pull request.

Sorry for the lost time.

**Comment by rain-1** [comment]
That's ok! I'm glad we tried.

**Pull request closed without merging**
