### PR TITLE
change make to ./make and add ground to verbose debugging support

### PR DESCRIPTION
**Pull request by petrolifero**
pegvm-verbose is a boolean that control if, when executing the code
will show the message "go inside number rule" when enter the number
rule code.

I don't know how to show this. I try using pegvm-current-rule, but
is a procedure. I see that format-id can transform from symbols to
identifiers, but how to transform to string, so we can display?

### CODE REVIEW

**Comment by petrolifero** [comment]
I understand : `(format "GO inside ~a" (symbol->string (syntax->datum #'rule-name)))`

**Comment by petrolifero** [comment]
But I am having problems with display : 
```

diff --git a/peg.rkt b/peg.rkt
index fdf4764..269ffb7 100644
--- a/peg.rkt
+++ b/peg.rkt
@@ -242,6 +242,7 @@
                    [body (peg-compile #'exp #'sk^)]
                    [action (if (syntax-e #'has-action?) #'action #'res)])
        #'(define (name sk)
+          (when pegvm-verbose (begin (display (format "GO inside ~a" (symbol->string (syntax->datum #'rule-name)))) (newline)))
            (parameterize ([pegvm-current-rule 'name])
              (let* bindings
                (let ((sk^ (lambda (res) (sk action))))
```

this works, when I use (peg number "123") they print "GO inside number", but the test suite breaks.

But go outside I dont know how to do. I transform the continuation? Change peg-compile? When I put in the end, after body, they break, problaby because the code expect the function to return what body returns.

**Comment by petrolifero** [comment]
I cant change peg-compile because they do recursive call, so will print outside a log of times.

I think(Mean I am testing) create a second function, that only will be called by a rule.

So

peg-rule:number call peg-compile-aux that call peg-compile that call peg-compile ....

In this way, I think the display will only print once.

**Comment by rain-1** [comment]
Making a new parameter as you did with `pegvm-verbose` seems like the correct thing to do.

**Comment by rain-1** [comment]
It's confusing that the tests break, since `pegvm-verbose` is `#f` by default.

**Comment by rain-1** [comment]
Instead of using `#f` and `#t` for `pegvm-verbose`, why don't we use `#f` and integers, that are use to indent the display depth so that the call tree can be seen visually.

**Comment by petrolifero** [comment]
Good ideia.

The verbose start with 0, and with peg-compile we change verbose to verbose+1?

I dont see if this maybe break because of continuations.

**Comment by petrolifero** [comment]
This break with you as well? Because can be a problem with my enviroment. I am using racket 6.11 yet

**Comment by petrolifero** [comment]
How the rules can be written?

`A -> B C;` will be like : 

```
A
   B
   C
```

???

if so, how can be represented `A-> B / C` ?? And `A -> !B` ??

there's need to construct a bijective function between print and rule?
In other words, if `A -> B C` result in the print above, `A -> B / C ` will result in a different print ?

**Comment by petrolifero** [comment]
If I understand correctly, when we call `A`, when `A -> B C`, the `A` rule need to transfer a different continuation to B and C evaluation. In this way, the code can live with little modification, respect the code's spirit, and the print can process uniformily between any call.

**Comment by rain-1** [comment]
I'm not really sure. Maybe there's a way to use rackets tracing features, then we don't have to write any new code for debugging?

**Comment by petrolifero** [comment]
I do `define-peg` create two functions, one for debug.
Now, for some reason that i can't figured out, they are only entry on debug function

**Comment by petrolifero** [comment]
define-peg create two functions, one with trace and one without.

In run-time, a function will verify pegvm-verbose when she need to call another parser function in order to decide if call a trace-based or a normal

**Comment by rain-1** [comment]
Great that you're working on this!

I don't like the approach of defining 2 versions of each function though, because it creates double the amount of code after macro-expansion.

I'll try to think about other ways a debug switch may be achieved.

**Comment by petrolifero** [comment]
Of course I am working on this. Is very cool :) Is a great problem.

Well, I try don't create two functions, but fail. When I don't create 2 functions, what happen was : in run-time, (i.e when `(peg exp ...)` was called), We need to call trace on a function to activate debug options, but throw a error that we can't "set! on module-required functions", so we can't use trace on a function if this function was required by a extern module.

That was the problem that, when I define a debug function was resolved. Because with this, I do trace inside the module, in compile-time, and don't in run-time, in peg time.

I'm not advocating this position, I know it's bad, I just found it good to explain why I took this strange kind of attitude :)

**Comment by petrolifero** [comment]
Tomorrow I will try again to fix the problem. I think is better to create the double of functions than don't have this debug option. After that, We will can see better ways to do that, what you think about?

Another thing : Can you create a milestone to the next release? Will be good to the project to priorize issues, and i will like a lot because I use racket-peg in a serie of projects, so I can expect more ou less what will be avaliable.

**Comment by rain-1** [comment]
Yeah, good idea for a milestone! We can do a new release soon. I will work on the documentation.

**Comment by petrolifero** [comment]
Is done.

**Comment by petrolifero** [comment]
The only point is that trace don't put tabs before tail-call.

So, when We do `(peg sum "12+13" #t)`  he print number in the same level of indentation of sum.

**Comment by petrolifero** [comment]
I try to fix the problem of indentation doing `(values (rule sk))` instead of `(rule sk)` in the call, but as the final thing that was done was call the sk, instead of something like: 

sum
  number
  number

show something like: 

sum
  number
    number

**Comment by petrolifero** [comment]
Probably your comment that pegvm-verbose be a number will control that. If you like the way that is going, I will try to put this change in the code(pegvm becomes a number and control indentation)

**Comment by rain-1** [comment]
You are doing good with the debug mode

**Comment by rain-1** [comment]
I've made an attempt at indenting the debug info, but it isn't working how it should. It just indents everything more and more. I was aiming to get something like this:

```
;peg-rule:local
￼ ; peg-rule:sum
￼ ;  peg-rule:number
￼ ;  peg-rule:number
￼ ; peg-rule:sum
￼ ;  peg-rule:number
￼ ;  peg-rule:number
```

**Comment by petrolifero** [comment]
In fact, we need to add to or subtract from pegvm-verbose in the compilation of `and, or`, etc.

Something that put the add instruction in the right places

**Comment by rain-1** [comment]
Maybe it would be best to not do the indentation. If it can't be implemented in an easy way.

**Comment by petrolifero** [comment]
without indentation, the purpose of debug will be compromise, right?

**Comment by petrolifero** [comment]
Why merge this pull request?

Is not working, right?

**Comment by rain-1** [comment]
It must have merged when I merged the other one

**Pull request merged**
