### PR TITLE
Add require

### PR DESCRIPTION
**Pull request by petrolifero**
Before the refact, we need to edit peg-in-peg, peg-in-peg-expanded, the docs, add tests and peg->result.

Now, when I do a contribution, what are the files that I need to edit? I need to put peg->result or use semantic actions?

### CODE REVIEW

**Comment by rain-1** [comment]
peg-in-peg.peg will not use semantic actions, the relevant part is https://github.com/rain-1/racket-peg/blob/master/peg-to-scheme.rkt#L41 it should be OK to read any s-exp, no need for & to check if it's a require. if it's not require peg-to-scheme can error. or maybe even some defines are ok too?

**Comment by petrolifero** [comment]
Well, If we allow arbitrary s-exp, then the user can define functions, structs, and other things.

In fact, peg will be a extension of racket, with grammar in the end, instead of a language to define this grammar.

Above is just a matter of fact, but what you think about this consequence? You know my preference (idiomatic constructs, peg as a language separated from racket), but I don't know if there's something that I can't see here. What do you think?

**Comment by rain-1** [comment]
Maybe it will be good to be able to define things! Like a helper function, or a large constant (e.g. the operator lookup table). I think we should try it out!

**Comment by petrolifero** [comment]
Ok, Tomorrow I will work on this. Can I use the s-exp as a example, defining the lookup on top, what do you think?

**Comment by petrolifero** [comment]
I need to do this later, because of some personal business. I will back soon

**Comment by petrolifero** [comment]
added. Some tests are broken, because of change of import to require, but the lib works well

**Comment by petrolifero** [comment]
this works : 

```
#lang peg

(require rackunit);
(struct add (a b));

_ < [ \t\n]* ;
```

**Comment by rain-1** [comment]
This is looking very promising.

Currently I cannot do `make install` on this branch without errors.

**Comment by petrolifero** [comment]
Yes, I am still working on the tests.

**Comment by petrolifero** [comment]
Correct now. Is just a lack of `_` after s-exp

**Comment by petrolifero** [comment]
There's just error on the docs but this is not special in this feature. The documentation has had this problem for a long time

**Pull request merged**
